import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const inter = Inter({
  subsets:['latin'],
  weight:['300', '400', '500', '600', '700','800', '900']
})
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`h-full antialiased ${inter.className}` }
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
        attribute='class'
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange   
        >{children}</ThemeProvider>
      </body>
    </html>
  );
}
